title: "cat-clipboard-launcher"
description: "cat-clipboard-launcher"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-clipboard-launcher
plugins:
  - jekyll-sitemap
